### ISSUE TITLE
keep on seeing "Failed to load source map" and "Sourcemap points to missing source files"

### ISSUE THREAD

**Issue by btoaelbore** [eirslett/storybook-builder-vite#176]
- when running storybook i keep on seeing warnings (Please see below screenshot)
- but when running `vite` dev it works fine without warning, not sure if i missing something ins storybook config

Clone and Install
```sh
git clone https://github.com/aelbore/vite-lit-stater
cd vite-lit-starter
git checkout bug-sourcemap
yarn install
```

Running Storybook
```
yarn storybook
```

Running Vite Dev
```
yarn serve
```

![image](https://user-images.githubusercontent.com/86104450/145421877-9c0bb769-2e8f-494b-af41-59976510b930.png)

**Comment by IanVS** [comment]
The error about pointing to missing source files is most likely an issue in https://www.npmjs.com/package/rollup-plugin-lit-transformer.  The vite react plugin had a similar issue a while back, which was fixed by https://github.com/vitejs/vite/pull/5587.

The other `Failed to load source map` log messages should clear up if you add the `new dependencies found` to your `optimizeDeps.include`, see https://github.com/eirslett/storybook-builder-vite/issues/173#issuecomment-989264127 for an example of how this can be done.

**Comment by IanVS** [comment]
Can you explain what `Failed error` you are seeing?  Have you tried clearing the vite cache and running storybook with `--no-manager-cache`?  Are you still seeing any messages like `new dependencies found` in the terminal?

**Comment by btoaelbore** [comment]
> Can you explain what `Failed error` you are seeing? Have you tried clearing the vite cache and running storybook with `--no-manager-cache`? Are you still seeing any messages like `new dependencies found` in the terminal?

@IanVS Same error above, and yes i tried `--no-manager-cache` again same error above, yes im still seeing message `new dependencies found` in terminal.

anyway storybook works fine and run ok, but the errors/warnings is annoying everytime you start the storybook it has warning and errors. 

do you have idea how to disable or to hide this warnings?

**Comment by IanVS** [comment]
You'll need to add the new dependencies that vite is finding to your `optimizeDeps.include` array, as shown in the comment I linked to earlier.

**Comment by btoaelbore** [comment]
> You'll need to add the new dependencies that vite is finding to your `optimizeDeps.include` array, as shown in the comment I linked to earlier.

i did add already but same error :)

**Comment by IanVS** [comment]
@btoaelbore it looks like you forgot to spread the existing `config.optimizeDeps.include` that the builder provides.  Here's a diff that should get you up and running with no errors

```diff
diff --git a/package.json b/package.json
index 683fec21c198ef251f2b31698a0e79f5e3881003..0bebb4eb64e12cb212d5f503fdc4cfca4442ab23 100644
--- a/package.json
+++ b/package.json
@@ -20,6 +20,7 @@
   },
   "homepage": "https://github.com/aelbore/vite-lit-stater#readme",
   "devDependencies": {
+    "@mdx-js/react": "^1.6.22",
     "@qoi/build": "^0.0.18",
     "@qoi/cli": "^0.0.20",
     "@qoi/types": "^0.0.2",
diff --git a/.storybook/main.js b/.storybook/main.js
index cd65f545b87f0e5db659295dc87cd82f576bf4cd..8d3b2cc9d6dcff85b894a2d2fab6e72ee772ecaa 100644
--- a/.storybook/main.js
+++ b/.storybook/main.js
@@ -36,12 +36,14 @@ const config = {
     config.plugins.push(litcss())
     config.optimizeDeps = {
       include: [
+        ...(config.optimizeDeps?.include || []),
         "lit-html",
         "lit-element",
         "lit-html/directive-helpers.js",
         "@lit/reactive-element",
         "@lit/reactive-element/css-tag.js",
-        "ansi-to-html/lib/ansi_to_html.js"
+        "ansi-to-html/lib/ansi_to_html.js",
+        "@storybook/web-components",
       ],
       entries: [`${path.relative(config.root, path.resolve(__dirname, '../stories'))}/**/*.stories.ts`],
     }

```

**Comment by btoaelbore** [comment]
@IanVS i did add `@storybook/web-components` you can check here `https://github.com/aelbore/vite-lit-stater/blob/bug-sourcemap/.storybook/main.js`
its not int he repo that i add `config.optimizeDeps.include` but in my local env i did add it same error above.

have you play around with the repository above? 
or maybe i will create a  video for the bug yeah i will create a video for it.

**Comment by btoaelbore** [comment]
@IanVS I deleted my comment, many thanks it works now for me weeew my bad. 
i can close this issue again thanks and good job this this library builder.
